/**
 * pi-saia-plugin: SAIA (Academic Cloud Hessen) provider registration.
 *
 * Registers the SAIA provider with all models from the live SAIA API.
 * API key is read from auth.json (key: "saia"), $SAIA_API_KEY, or /login saia.
 *
 * Install: pi install /path/to/pi-saia-plugin
 * Reload:  /reload
 *
 * This file is auto-generated by scripts/sync-saia-models.sh
 * Last sync: 2026-10-07 05:46:30
 */

import type { ExtensionAPI, ProviderModelConfig } from "@earendil-works/pi-coding-agent";

// ---------------------------------------------------------------------------
// Model catalog — Auto-synced from SAIA API
// ---------------------------------------------------------------------------

export const SAIA_MODELS: ProviderModelConfig[] = [

  // ── General ────────────────────────────────────────────────────
  {
    id: "apertus-70b-instruct-2509",
    name: "Apertus 70B Instruct 2509 (SAIA)",
    reasoning: false,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 65000,
    maxTokens: 8192,
  },
  {
    id: "deepseek-v4-flash-0731",
    name: "DeepSeek V4 Flash 0731 (SAIA)",
    reasoning: true,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 1000000,
    maxTokens: 32768,
  },

  // ── Agentic ────────────────────────────────────────────────────
  {
    id: "devstral-2-123b-instruct-2512",
    name: "Devstral 2 123B Instruct 2512 (SAIA)",
    reasoning: false,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 16384,
  },

  // ── General ────────────────────────────────────────────────────
  {
    id: "gemma-4-31b-it",
    name: "Gemma 4 31B Instruct (SAIA)",
    reasoning: false,
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 8192,
  },

  // ── Agentic ────────────────────────────────────────────────────
  {
    id: "glm-5.3-flash",
    name: "GLM 5.3 Flash (SAIA)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 1000000,
    maxTokens: 32768,
  },

  // ── General ────────────────────────────────────────────────────
  {
    id: "meta-llama-3.1-8b-instruct",
    name: "Llama 3.1 8B Instruct (SAIA)",
    reasoning: false,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 128000,
    maxTokens: 4096,
  },

  // ── Agentic ────────────────────────────────────────────────────
  {
    id: "mistral-medium-3.5-128b",
    name: "Mistral Medium 3.5 128B (SAIA)",
    reasoning: false,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 8192,
  },

  // ── Large Context ────────────────────────────────────────────────────
  {
    id: "openai-gpt-oss-120b",
    name: "GPT OSS 120B (SAIA)",
    reasoning: true,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 128000,
    maxTokens: 8192,
  },

  // ── General ────────────────────────────────────────────────────
  {
    id: "qwen3-30b-a3b-instruct-2507",
    name: "Qwen 3 30B A3B Instruct 2507 (SAIA)",
    reasoning: false,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 16384,
  },

  // ── Reasoning ────────────────────────────────────────────────────
  {
    id: "qwen3.5-397b-a17b",
    name: "Qwen 3.5 397B A17B (SAIA)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 32768,
  },
  {
    id: "qwen3.6-35b-a3b",
    name: "Qwen 3.6 35B A3B (SAIA)",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 262000,
    maxTokens: 16384,
  },
  {
    id: "qwen3.8-27b",
    name: "Qwen 3.8 27B (SAIA)",
    reasoning: true,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 262000,
    maxTokens: 32768,
  },

  // ── Coder ────────────────────────────────────────────────────
  {
    id: "qwen3-coder-next",
    name: "Qwen 3 Coder Next (SAIA)",
    reasoning: false,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 16384,
  },

  // ── Vision ────────────────────────────────────────────────────
  {
    id: "qwen3-omni-30b-a3b-instruct",
    name: "Qwen 3 Omni 30B A3B Instruct (SAIA)",
    reasoning: false,
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 4096,
  },

  // ── Aliases (convenience shortcuts) ──────────────────────────────────
  {
    id: "best-for-agentic",
    name: "best-for-agentic → glm-5.3-flash",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 1000000,
    maxTokens: 32768,
  },
  {
    id: "best-for-reasoning",
    name: "best-for-reasoning → qwen3.5-397b-a17b",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 32768,
  },
  {
    id: "best-quality",
    name: "best-quality → qwen3.5-397b-a17b",
    reasoning: true,
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 32768,
  },
  {
    id: "fastest-reasoning",
    name: "fastest-reasoning → qwen3.8-27b",
    reasoning: true,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 262000,
    maxTokens: 32768,
  },
  {
    id: "fastest",
    name: "fastest → meta-llama-3.1-8b-instruct",
    reasoning: false,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 128000,
    maxTokens: 4096,
  },
  {
    id: "budget",
    name: "budget → deepseek-v4-flash-0731",
    reasoning: true,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 1000000,
    maxTokens: 32768,
  },
  {
    id: "best-for-vision",
    name: "best-for-vision → qwen3.8-27b",
    reasoning: true,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 262000,
    maxTokens: 32768,
  },
  {
    id: "best-for-coding",
    name: "best-for-coding → qwen3-coder-next",
    reasoning: false,
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 16384,
  },
];

// ---------------------------------------------------------------------------
// Provider registration
// ---------------------------------------------------------------------------

export default function (pi: ExtensionAPI) {
  pi.registerProvider("saia", {
    name: "SAIA Academic Cloud",
    baseUrl: "https://chat-ai.academiccloud.de/v1",
    apiKey: "$SAIA_API_KEY",
    api: "openai-completions",
    models: SAIA_MODELS,
  });
}
