/**
 * pi-saia-plugin: SAIA (Academic Cloud Hessen) provider registration.
 *
 * Registers the SAIA provider with every model from the live SAIA API.
 * API key is read from $SAIA_API_KEY, the auth.json entry for provider "saia"
 * (`pi auth` / `/login saia`), or the value pi resolves from the config.
 *
 * Install: pi install /path/to/pi-saia-plugin
 * Reload:  /reload
 *
 * AUTO-GENERATED by scripts/sync-saia-models.sh — edit the generator, not this
 * file. Facts come from data/saia-models.json (live API + GWDG docs + the
 * curated scripts/reasoning-models.json); output limits, thinking-level maps,
 * categories and the alias table are the generator's "taste" tables.
 *
 * Last sync: 2026-10-07 07:29:48
 */

import type { ExtensionAPI, ProviderModelConfig } from "@earendil-works/pi-coding-agent";

/** Provider id every model of this plugin is registered under. */
export const SAIA_PROVIDER_ID = "saia";

/** Canonical base URL of the OpenAI-compatible SAIA endpoint. */
export const SAIA_BASE_URL = "https://chat-ai.academiccloud.de/v1";

/**
 * Environment variable that overrides {@link SAIA_BASE_URL}.
 *
 * Useful behind an institutional gateway/proxy (LiteLLM, Kong, an SSH tunnel)
 * and required by the hermetic wire-protocol test, which points the provider at
 * a local mock so aliases and the `developer` role can be verified without a key
 * and without touching the network.
 */
export const SAIA_BASE_URL_ENV = "SAIA_BASE_URL";

/**
 * Effective base URL: $SAIA_BASE_URL when set and non-blank, otherwise the
 * canonical endpoint. Trailing slashes are trimmed so `http://host/v1/` and
 * `http://host/v1` behave identically.
 */
export function resolveBaseUrl(env: Record<string, string | undefined> = process.env): string {
  const override = env[SAIA_BASE_URL_ENV];
  if (typeof override !== "string" || override.trim().length === 0) {
    return SAIA_BASE_URL;
  }
  const trimmed = override.trim().replace(/\/+$/, "");
  return trimmed.length > 0 ? trimmed : SAIA_BASE_URL;
}

// ---------------------------------------------------------------------------
// Model catalog — facts from data/saia-models.json
// ---------------------------------------------------------------------------

export const SAIA_MODELS: ProviderModelConfig[] = [

  // ── General ──────────────────────────────────────────
  {
    id: "apertus-70b-instruct-2509",
    name: "Apertus 70B Instruct 2509 (SAIA)",
    reasoning: false,
    compat: { supportsDeveloperRole: false },
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 65000,
    maxTokens: 8192,
  },
  {
    id: "deepseek-v4-flash-0731",
    name: "DeepSeek V4 Flash 0731 (SAIA)",
    reasoning: true,
    thinkingLevelMap: {"minimal":"low","low":"low","medium":"high","high":"high","xhigh":"max","max":"max"},
    compat: { supportsDeveloperRole: false },
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 1000000,
    maxTokens: 32768,
  },

  // ── Agentic ──────────────────────────────────────────
  {
    id: "devstral-2-123b-instruct-2512",
    name: "Devstral 2 123B Instruct 2512 (SAIA)",
    reasoning: false,
    compat: { supportsDeveloperRole: false },
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 16384,
  },

  // ── General ──────────────────────────────────────────
  {
    id: "gemma-4-31b-it",
    name: "Gemma 4 31B Instruct (SAIA)",
    reasoning: false,
    compat: { supportsDeveloperRole: false },
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 8192,
  },

  // ── Agentic ──────────────────────────────────────────
  {
    id: "glm-5.3-flash",
    name: "GLM 5.3 Flash (SAIA)",
    reasoning: true,
    thinkingLevelMap: {"minimal":"low","low":"low","medium":"high","high":"high","xhigh":"max","max":"max"},
    compat: { supportsDeveloperRole: false },
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 1000000,
    maxTokens: 32768,
  },

  // ── General ──────────────────────────────────────────
  {
    id: "meta-llama-3.1-8b-instruct",
    name: "Llama 3.1 8B Instruct (SAIA)",
    reasoning: false,
    compat: { supportsDeveloperRole: false },
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 128000,
    maxTokens: 4096,
  },

  // ── Agentic ──────────────────────────────────────────
  {
    id: "mistral-medium-3.5-128b",
    name: "Mistral Medium 3.5 128B (SAIA)",
    reasoning: false,
    compat: { supportsDeveloperRole: false },
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 8192,
  },

  // ── Large Context ──────────────────────────────────────────
  {
    id: "openai-gpt-oss-120b",
    name: "GPT OSS 120B (SAIA)",
    reasoning: true,
    thinkingLevelMap: {"minimal":"low","low":"low","medium":"medium","high":"high","xhigh":"high","max":"high"},
    compat: { supportsDeveloperRole: false },
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 128000,
    maxTokens: 8192,
  },

  // ── General ──────────────────────────────────────────
  {
    id: "qwen3-30b-a3b-instruct-2507",
    name: "Qwen 3 30B A3B Instruct 2507 (SAIA)",
    reasoning: false,
    compat: { supportsDeveloperRole: false },
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 16384,
  },

  // ── Coder ──────────────────────────────────────────
  {
    id: "qwen3-coder-next",
    name: "Qwen 3 Coder Next (SAIA)",
    reasoning: false,
    compat: { supportsDeveloperRole: false },
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 16384,
  },

  // ── Vision ──────────────────────────────────────────
  {
    id: "qwen3-omni-30b-a3b-instruct",
    name: "Qwen 3 Omni 30B A3B Instruct (SAIA)",
    reasoning: false,
    compat: { supportsDeveloperRole: false },
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 4096,
  },

  // ── Reasoning ──────────────────────────────────────────
  {
    id: "qwen3.5-397b-a17b",
    name: "Qwen 3.5 397B A17B (SAIA)",
    reasoning: true,
    compat: { supportsDeveloperRole: false },
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 256000,
    maxTokens: 32768,
  },
  {
    id: "qwen3.6-35b-a3b",
    name: "Qwen 3.6 35B A3B (SAIA)",
    reasoning: true,
    compat: { supportsDeveloperRole: false },
    input: ["text", "image"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 262000,
    maxTokens: 16384,
  },
  {
    id: "qwen3.8-27b",
    name: "Qwen 3.8 27B (SAIA)",
    reasoning: true,
    compat: { supportsDeveloperRole: false },
    input: ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: 262000,
    maxTokens: 32768,
  },
];

// ---------------------------------------------------------------------------
// Aliases
// ---------------------------------------------------------------------------
//
// SAIA has no concept of aliases: it 404s on any model id it does not serve.
// So an alias is a *local* name that must be rewritten to its target before the
// request leaves pi — see the before_provider_request hook below.

/** Convenience alias → real SAIA model id. */
export const SAIA_ALIASES: Record<string, string> = {
  "best-for-coding": "qwen3-coder-next",
  "best-for-reasoning": "qwen3.5-397b-a17b",
  "best-quality": "qwen3.5-397b-a17b",
  "best-for-vision": "qwen3.8-27b",
  "best-for-agentic": "glm-5.3-flash",
  "fastest": "meta-llama-3.1-8b-instruct",
  "fastest-reasoning": "qwen3.8-27b",
  "budget": "deepseek-v4-flash-0731",
};

/**
 * Alias entries projected from their targets.
 *
 * Deriving these from `SAIA_MODELS` instead of hand-writing duplicates means an
 * alias can never advertise different capabilities than the model it points at.
 */
export const SAIA_ALIAS_MODELS: ProviderModelConfig[] = Object.entries(SAIA_ALIASES).map(
  ([alias, targetId]) => {
    const target = SAIA_MODELS.find((model) => model.id === targetId);
    if (!target) {
      throw new Error(`SAIA alias "${alias}" points at unknown model "${targetId}"`);
    }
    return { ...target, id: alias, name: `${alias} → ${targetId}` };
  },
);

/** Everything registered with pi: the real models plus the alias entries. */
export const SAIA_ALL_MODELS: ProviderModelConfig[] = [...SAIA_MODELS, ...SAIA_ALIAS_MODELS];

// ---------------------------------------------------------------------------
// Provider registration
// ---------------------------------------------------------------------------

/**
 * Resolve a requested model id to the id that must be sent to SAIA.
 *
 * Returns `undefined` when the request is not for a SAIA alias, so callers can
 * treat it as "leave the payload alone".
 */
export function rewriteAliasModel(requestedModel: unknown, providerId?: string): string | undefined {
  if (providerId !== undefined && providerId !== SAIA_PROVIDER_ID) {
    return undefined;
  }
  if (typeof requestedModel !== "string") {
    return undefined;
  }
  return SAIA_ALIASES[requestedModel];
}

/**
 * Rewrite the `model` field of an outgoing provider payload if it is an alias.
 * Returns the original payload untouched when no rewrite applies.
 */
export function applyAliasToPayload(payload: unknown, providerId?: string): unknown {
  if (typeof payload !== "object" || payload === null) {
    return payload;
  }
  const target = rewriteAliasModel((payload as { model?: unknown }).model, providerId);
  if (!target) {
    return payload;
  }
  return { ...(payload as Record<string, unknown>), model: target };
}

export default function (pi: ExtensionAPI) {
  pi.registerProvider(SAIA_PROVIDER_ID, {
    name: "SAIA Academic Cloud",
    baseUrl: resolveBaseUrl(),
    apiKey: "$SAIA_API_KEY",
    api: "openai-completions",
    models: SAIA_ALL_MODELS,
  });

  // SAIA 404s on alias ids, so map them to their real model id on the wire.
  pi.on("before_provider_request", (event, ctx) =>
    applyAliasToPayload(event.payload, ctx.model?.provider),
  );
}
