#!/usr/bin/env bash
#
# SAIA model catalog sync for pi-saia-plugin.
#
# Two artifacts, one source of truth:
#
#   data/saia-models.json    facts, generated by scripts/collect-saia-model-info.mjs
#                            (live API + GWDG docs + curated reasoning-models.json)
#   extensions/index.ts      the pi provider registration, generated from those
#                            facts plus the "taste" tables at the top of this file
#                            (output limits, categories, aliases)
#
# Usage:
#   ./scripts/sync-saia-models.sh                 # refresh facts, regenerate index.ts
#   ./scripts/sync-saia-models.sh --check         # verify both are current (see exit codes)
#   ./scripts/sync-saia-models.sh --out FILE      # write the TS somewhere else
#   ./scripts/sync-saia-models.sh --print-ts      # write the TS to stdout
#
# Exit codes (--check):
#   0  both artifacts match the live API
#   1  drift: an artifact is stale
#   2  bad usage
#   3  facts could not be determined (no key, API unreachable, collector broken)
#
# 1 and 3 are deliberately distinct: a transient upstream failure is not drift,
# so callers (CI, the smoke suite) can tell a flaky network from a stale catalog
# instead of reporting the first as the second.
#
# Environment:
#   SAIA_API_KEY      API key for the live model list (collector)
#   SAIA_API_URL      Override the models endpoint
#   SAIA_MODELS_DATA  Use this data/saia-models.json instead of refreshing it.
#                     Makes the generator hermetic (no key, no network), which is
#                     what the offline tests and CI use.
#
# Requires bash 3.2+ (macOS default) — no associative arrays, no ${var,,}.

set -euo pipefail

EXIT_OK=0
EXIT_STALE=1
EXIT_USAGE=2
EXIT_UNAVAILABLE=3

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(dirname "$SCRIPT_DIR")"
EXTENSIONS_FILE="$PLUGIN_DIR/extensions/index.ts"
DATA_FILE="$PLUGIN_DIR/data/saia-models.json"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
# All logging goes to stderr so --print-ts emits only the generated file.
print_info()  { echo -e "${GREEN}[INFO]${NC} $1" >&2; }
print_warn()  { echo -e "${YELLOW}[WARN]${NC} $1" >&2; }
print_error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

usage() {
    sed -n '3,30p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

# ---------------------------------------------------------------------------
# Taste: output limits (id|max_tokens). Everything else in the generated file is
# a fact derived from data/saia-models.json. Unknown models get a sane default
# instead of being skipped.
# ---------------------------------------------------------------------------

MAX_TOKENS=(
    "apertus-70b-instruct-2509|8192"
    "deepseek-v4-flash-0731|32768"
    "devstral-2-123b-instruct-2512|16384"
    "gemma-4-31b-it|8192"
    "glm-5.3-flash|32768"
    "meta-llama-3.1-8b-instruct|4096"
    "mistral-medium-3.5-128b|8192"
    "openai-gpt-oss-120b|8192"
    "qwen3-30b-a3b-instruct-2507|16384"
    "qwen3-coder-next|16384"
    "qwen3-omni-30b-a3b-instruct|4096"
    "qwen3.5-397b-a17b|32768"
    "qwen3.6-35b-a3b|16384"
    "qwen3.8-27b|32768"
)
MAX_TOKENS_DEFAULT="16384"

# Taste: aliases (alias|target), in a fixed order. A plain list, not
# `declare -A`: macOS ships bash 3.2, where associative arrays do not exist, and
# the array iteration order of an associative array is not stable anyway — which
# would make the generated file churn on every run and `--check` always report
# drift.
ALIAS_ROWS=(
    "best-for-coding|qwen3-coder-next"
    "best-for-reasoning|qwen3.5-397b-a17b"
    "best-quality|qwen3.5-397b-a17b"
    "best-for-vision|qwen3.8-27b"
    "best-for-agentic|glm-5.3-flash"
    "fastest|meta-llama-3.1-8b-instruct"
    "fastest-reasoning|qwen3.8-27b"
    "budget|deepseek-v4-flash-0731"
)

max_tokens_for() {
    local want="$1" row
    for row in "${MAX_TOKENS[@]}"; do
        case "$row" in
            "$want|"*) printf '%s' "${row#*|}"; return 0 ;;
        esac
    done
    printf '%s' "$MAX_TOKENS_DEFAULT"
}

# Categorize model based on ID
categorize() {
    case "$1" in
        *thinking*|*r1*|qwen3.5-*|qwen3.6-35b-a3b|qwen3.8-27b) echo "reasoning" ;;
        *coder*)                                              echo "coder" ;;
        *omni*|*vl-*|*vision*|internvl*)                      echo "vision" ;;
        devstral*|mistral-medium*|glm-5.3-flash)              echo "agentic" ;;
        *120b|*128b|*235b|*675b)                              echo "large-context" ;;
        *)                                                    echo "general" ;;
    esac
}

category_title() {
    echo "$1" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1'
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

CHECK_ONLY=0
PRINT_TS=0
OUT_FILE="$EXTENSIONS_FILE"

while [ $# -gt 0 ]; do
    case "$1" in
        --check)    CHECK_ONLY=1; shift ;;
        --print-ts) PRINT_TS=1; shift ;;
        --out)
            [ $# -ge 2 ] || { print_error "--out needs a path"; exit $EXIT_USAGE; }
            OUT_FILE="$2"; shift 2 ;;
        --help|-h)  usage; exit $EXIT_OK ;;
        *)          print_error "unknown argument: $1"; usage; exit $EXIT_USAGE ;;
    esac
done

command -v jq >/dev/null 2>&1 || {
    print_error "jq is required but not installed"
    print_info "Install it with: brew install jq   (or apt-get install jq)"
    exit $EXIT_UNAVAILABLE
}

# ---------------------------------------------------------------------------
# Facts
# ---------------------------------------------------------------------------

WORK_DIR=""
cleanup() { [ -n "$WORK_DIR" ] && rm -rf "$WORK_DIR"; }
trap cleanup EXIT

WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/saia-sync.XXXXXX")"

FACTS_FILE="$DATA_FILE"
if [ -n "${SAIA_MODELS_DATA:-}" ]; then
    # Hermetic mode: use the facts we were handed.
    [ -f "$SAIA_MODELS_DATA" ] || { print_error "SAIA_MODELS_DATA not found: $SAIA_MODELS_DATA"; exit $EXIT_UNAVAILABLE; }
    FACTS_FILE="$SAIA_MODELS_DATA"
    print_info "Using SAIA_MODELS_DATA=$SAIA_MODELS_DATA"
elif [ "$CHECK_ONLY" -eq 1 ]; then
    # Collect into a temp file so a check never dirties the tree it checks.
    print_info "Collecting live facts (check mode — nothing is written to the repo)"
    if ! node "$SCRIPT_DIR/collect-saia-model-info.mjs" --out "$WORK_DIR/saia-models.json" >"$WORK_DIR/collect.log" 2>&1; then
        print_error "could not collect live model facts"
        sed -n '1,10p' "$WORK_DIR/collect.log"
        exit $EXIT_UNAVAILABLE
    fi
    FACTS_FILE="$WORK_DIR/saia-models.json"
else
    if command -v node >/dev/null 2>&1 && node "$SCRIPT_DIR/collect-saia-model-info.mjs" --out "$DATA_FILE"; then
        print_info "Refreshed data/saia-models.json (live API + GWDG docs)"
    elif [ -f "$DATA_FILE" ]; then
        print_warn "Collector unavailable — using committed data/saia-models.json"
    else
        print_error "No data/saia-models.json and collector failed"
        exit $EXIT_UNAVAILABLE
    fi
fi

[ -f "$FACTS_FILE" ] || { print_error "facts file not found: $FACTS_FILE"; exit $EXIT_UNAVAILABLE; }
jq -e '.models' "$FACTS_FILE" >/dev/null 2>&1 || { print_error "$FACTS_FILE is not a model catalog"; exit $EXIT_UNAVAILABLE; }

MODEL_COUNT="$(jq -r '.models | length' "$FACTS_FILE")"
print_info "Facts: $MODEL_COUNT models"

# fact_for <model-id> <jq expr over one model object>  (prints "null" if absent)
# NOTE: modalities are filtered to text|image — pi's ProviderModelConfig does
# not (yet) express video/audio inputs.
fact_for() {
    jq -cr --arg id "$1" \
        "first(.models[] | select(.id == \$id) | $2) // \"null\"" "$FACTS_FILE"
}

# thinking_map_for <model-id>
#
# pi's thinking levels are minimal|low|medium|high|xhigh|max, but SAIA's
# backends accept only a subset per model (openai-gpt-oss-120b rejects
# `minimal` with "not supported by Harmony", and pi clamps `xhigh`/`max` down to
# `high`, which makes maximum effort unreachable). Map every pi level onto the
# nearest *curated* supported value, using scripts/reasoning-models.json.
# Prints "null" for models whose reasoning API is not known — there, pi's own
# defaults apply.
thinking_map_for() {
    jq -c --arg id "$1" '
      first(.models[] | select(.id == $id) | .reasoning.effort.values) // null
      | if . == null or length == 0 or (map(type) | any(. != "string")) then null
        else . as $values
        | ["minimal", "low", "medium", "high", "xhigh", "max"] as $order
        | reduce ($order[]) as $lvl ({};
            . + { ($lvl): (
              # Prefer the same name; otherwise the nearest curated value in
              # canonical order, breaking ties towards more effort.
              if ($values | index($lvl)) != null then $lvl
              else ($order | index($lvl)) as $target
                | ($values
                   | map(. as $v | ($order | index($v)) as $rank
                         | { v: $v, d: (($rank - $target) | if . < 0 then -. else . end), rank: $rank })
                   | sort_by(.d, (0 - .rank))
                   | .[0].v)
              end ) })
        end' "$FACTS_FILE"
}

modalities_for() {
    jq -cr --arg id "$1" \
        'first(.models[] | select(.id == $id) | .input) // ["text"]
         | map(select(. == "text" or . == "image"))
         | if length == 0 then ["text"] else . end
         | map("\"" + . + "\"") | join(", ")' "$FACTS_FILE"
}

# ---------------------------------------------------------------------------
# Generate
# ---------------------------------------------------------------------------

TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S')"
TMP_TS="$WORK_DIR/index.ts"

{
    cat <<EOF
/**
 * pi-saia-plugin: SAIA (Academic Cloud Hessen) provider registration.
 *
 * Registers the SAIA provider with every model from the live SAIA API.
 * API key is read from \$SAIA_API_KEY, the auth.json entry for provider "saia"
 * (\`pi auth\` / \`/login saia\`), or the value pi resolves from the config.
 *
 * Install: pi install /path/to/pi-saia-plugin
 * Reload:  /reload
 *
 * AUTO-GENERATED by scripts/sync-saia-models.sh — edit the generator, not this
 * file. Facts come from data/saia-models.json (live API + GWDG docs + the
 * curated scripts/reasoning-models.json); output limits, thinking-level maps,
 * categories and the alias table are the generator's "taste" tables.
 *
 * Last sync: $TIMESTAMP
 */

import type { ExtensionAPI, ProviderModelConfig } from "@earendil-works/pi-coding-agent";

/** Provider id every model of this plugin is registered under. */
export const SAIA_PROVIDER_ID = "saia";

/** Canonical base URL of the OpenAI-compatible SAIA endpoint. */
export const SAIA_BASE_URL = "https://chat-ai.academiccloud.de/v1";

/**
 * Environment variable that overrides {@link SAIA_BASE_URL}.
 *
 * Useful behind an institutional gateway/proxy (LiteLLM, Kong, an SSH tunnel)
 * and required by the hermetic wire-protocol test, which points the provider at
 * a local mock so aliases and the \`developer\` role can be verified without a key
 * and without touching the network.
 */
export const SAIA_BASE_URL_ENV = "SAIA_BASE_URL";

/**
 * Effective base URL: \$SAIA_BASE_URL when set and non-blank, otherwise the
 * canonical endpoint. Trailing slashes are trimmed so \`http://host/v1/\` and
 * \`http://host/v1\` behave identically.
 */
export function resolveBaseUrl(env: Record<string, string | undefined> = process.env): string {
  const override = env[SAIA_BASE_URL_ENV];
  if (typeof override !== "string" || override.trim().length === 0) {
    return SAIA_BASE_URL;
  }
  const trimmed = override.trim().replace(/\/+\$/, "");
  return trimmed.length > 0 ? trimmed : SAIA_BASE_URL;
}

// ---------------------------------------------------------------------------
// Model catalog — facts from data/saia-models.json
// ---------------------------------------------------------------------------

export const SAIA_MODELS: ProviderModelConfig[] = [
EOF

    LAST_CATEGORY=""
    jq -r '.models[].id' "$FACTS_FILE" | sort | while read -r model_id; do
        [ -n "$model_id" ] || continue

        context="$(fact_for "$model_id" '.context_window.tokens')"
        if [ "$context" = "null" ] || [ "$context" = "" ]; then
            print_warn "No context-window facts for $model_id (skipping — update the GWDG docs or the collector)"
            continue
        fi

        description="$(fact_for "$model_id" '.name + " (SAIA)"')"
        reasoning="$(fact_for "$model_id" '.reasoning.supported == true | tostring')"
        [ "$reasoning" = "true" ] || reasoning="false"
        inputs="$(modalities_for "$model_id")"
        max_tokens="$(max_tokens_for "$model_id")"
        category="$(categorize "$model_id")"
        thinking_map="$(thinking_map_for "$model_id")"

        if [ "$category" != "$LAST_CATEGORY" ]; then
            echo ""
            echo "  // ── $(category_title "$category") ──────────────────────────────────────────"
            LAST_CATEGORY="$category"
        fi

        echo "  {"
        echo "    id: \"$model_id\","
        echo "    name: \"$description\","
        echo "    reasoning: $reasoning,"
        if [ "$thinking_map" != "null" ]; then
            echo "    thinkingLevelMap: $thinking_map,"
        fi
        # SAIA rejects the OpenAI "developer" role with
        # 400 {"message":"Unexpected message role."} — pi must fold it into
        # "system" instead.
        echo "    compat: { supportsDeveloperRole: false },"
        echo "    input: [$inputs],"
        echo "    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },"
        echo "    contextWindow: $context,"
        echo "    maxTokens: $max_tokens,"
        echo "  },"
    done

    cat <<'EOF'
];

// ---------------------------------------------------------------------------
// Aliases
// ---------------------------------------------------------------------------
//
// SAIA has no concept of aliases: it 404s on any model id it does not serve.
// So an alias is a *local* name that must be rewritten to its target before the
// request leaves pi — see the before_provider_request hook below.

/** Convenience alias → real SAIA model id. */
export const SAIA_ALIASES: Record<string, string> = {
EOF

    for row in "${ALIAS_ROWS[@]}"; do
        alias_name="${row%%|*}"
        target="${row#*|}"
        # Only emit an alias whose target is actually served (and known).
        if [ "$(fact_for "$target" '.id')" = "null" ]; then
            print_warn "alias $alias_name skipped: target $target is not in the facts"
            continue
        fi
        context="$(fact_for "$target" '.context_window.tokens')"
        if [ "$context" = "null" ] || [ "$context" = "" ]; then
            print_warn "alias $alias_name skipped: no context-window facts for $target"
            continue
        fi
        echo "  \"$alias_name\": \"$target\","
    done

    cat <<'EOF'
};

/**
 * Alias entries projected from their targets.
 *
 * Deriving these from `SAIA_MODELS` instead of hand-writing duplicates means an
 * alias can never advertise different capabilities than the model it points at.
 */
export const SAIA_ALIAS_MODELS: ProviderModelConfig[] = Object.entries(SAIA_ALIASES).map(
  ([alias, targetId]) => {
    const target = SAIA_MODELS.find((model) => model.id === targetId);
    if (!target) {
      throw new Error(`SAIA alias "${alias}" points at unknown model "${targetId}"`);
    }
    return { ...target, id: alias, name: `${alias} → ${targetId}` };
  },
);

/** Everything registered with pi: the real models plus the alias entries. */
export const SAIA_ALL_MODELS: ProviderModelConfig[] = [...SAIA_MODELS, ...SAIA_ALIAS_MODELS];

// ---------------------------------------------------------------------------
// Provider registration
// ---------------------------------------------------------------------------

/**
 * Resolve a requested model id to the id that must be sent to SAIA.
 *
 * Returns `undefined` when the request is not for a SAIA alias, so callers can
 * treat it as "leave the payload alone".
 */
export function rewriteAliasModel(requestedModel: unknown, providerId?: string): string | undefined {
  if (providerId !== undefined && providerId !== SAIA_PROVIDER_ID) {
    return undefined;
  }
  if (typeof requestedModel !== "string") {
    return undefined;
  }
  return SAIA_ALIASES[requestedModel];
}

/**
 * Rewrite the `model` field of an outgoing provider payload if it is an alias.
 * Returns the original payload untouched when no rewrite applies.
 */
export function applyAliasToPayload(payload: unknown, providerId?: string): unknown {
  if (typeof payload !== "object" || payload === null) {
    return payload;
  }
  const target = rewriteAliasModel((payload as { model?: unknown }).model, providerId);
  if (!target) {
    return payload;
  }
  return { ...(payload as Record<string, unknown>), model: target };
}

export default function (pi: ExtensionAPI) {
  pi.registerProvider(SAIA_PROVIDER_ID, {
    name: "SAIA Academic Cloud",
    baseUrl: resolveBaseUrl(),
    apiKey: "$SAIA_API_KEY",
    api: "openai-completions",
    models: SAIA_ALL_MODELS,
  });

  // SAIA 404s on alias ids, so map them to their real model id on the wire.
  pi.on("before_provider_request", (event, ctx) =>
    applyAliasToPayload(event.payload, ctx.model?.provider),
  );
}
EOF
} > "$TMP_TS"

# `set -e` inside a pipeline: the subshell above only fails if a write fails.
[ -s "$TMP_TS" ] || { print_error "generated file is empty"; exit $EXIT_UNAVAILABLE; }

# Drop the timestamp line so two runs are byte-identical.
strip_timestamp() {
    grep -v '^ \* Last sync:'
}

normalize_facts() {
    # Compare facts without volatile fields: `generated_at` changes every run and
    # `demand` (queue depth) changes between seconds.
    jq -S 'del(.generated_at) | .live.models |= map(del(.demand))' "$1"
}

if [ "$PRINT_TS" -eq 1 ]; then
    cat "$TMP_TS"
    exit $EXIT_OK
fi

if [ "$CHECK_ONLY" -eq 1 ]; then
    drift=0

    if [ -n "${SAIA_MODELS_DATA:-}" ] || [ "$FACTS_FILE" = "$DATA_FILE" ]; then
        if ! diff -q <(normalize_facts "$DATA_FILE") <(normalize_facts "$FACTS_FILE") >/dev/null 2>&1; then
            print_error "data/saia-models.json is stale"
            diff -u <(normalize_facts "$DATA_FILE") <(normalize_facts "$FACTS_FILE") | head -40
            drift=1
        fi
    fi

    if [ ! -f "$OUT_FILE" ]; then
        print_error "$OUT_FILE does not exist"
        exit $EXIT_STALE
    fi
    if ! diff -q <(strip_timestamp < "$OUT_FILE") <(strip_timestamp < "$TMP_TS") >/dev/null 2>&1; then
        print_error "$(basename "$OUT_FILE") is stale — run ./scripts/sync-saia-models.sh"
        diff -u <(strip_timestamp < "$OUT_FILE") <(strip_timestamp < "$TMP_TS") | head -60
        drift=1
    fi

    if [ "$drift" -eq 1 ]; then
        exit $EXIT_STALE
    fi
    print_info "catalog is up to date ($MODEL_COUNT models)"
    exit $EXIT_OK
fi

mkdir -p "$(dirname "$OUT_FILE")"
cp "$TMP_TS" "$OUT_FILE"
print_info "✓ wrote $OUT_FILE"
print_info "  models: $MODEL_COUNT   aliases: $(grep -c '^  "' "$OUT_FILE" || true)"
print_info "  timestamp: $TIMESTAMP"
