#!/usr/bin/env bash
set -euo pipefail

# SAIA Models Sync Script for pi-saia-plugin
# Fetches latest models from SAIA API and updates extensions/index.ts
# Run this periodically to keep the plugin in sync with SAIA

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(dirname "$SCRIPT_DIR")"
EXTENSIONS_FILE="$PLUGIN_DIR/extensions/index.ts"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# API configuration
SAIA_API_KEY="${SAIA_API_KEY:-}"
API_BASE_URL="${SAIA_API_URL:-https://chat-ai.academiccloud.de/v1}"

# Check for API key
if [[ -z "$SAIA_API_KEY" ]]; then
    print_error "SAIA_API_KEY environment variable not set"
    print_info "Set it with: export SAIA_API_KEY=your_key"
    print_info "Or use: /login saia in pi"
    exit 1
fi

print_info "Fetching latest SAIA models from $API_BASE_URL..."

# Fetch models from API
MODELS_JSON=$(curl -s --max-time 30 "$API_BASE_URL/models" \
    -H "Authorization: Bearer $SAIA_API_KEY")

if [[ -z "$MODELS_JSON" ]] || ! echo "$MODELS_JSON" | jq -e '.data' >/dev/null 2>&1; then
    print_error "Failed to fetch models from SAIA API"
    print_info "Response: $MODELS_JSON"
    exit 1
fi

MODEL_COUNT=$(echo "$MODELS_JSON" | jq -r '.data | length')
print_info "Found $MODEL_COUNT models from SAIA API"

# ── Facts vs taste ────────────────────────────────────────────────────────────
# Facts (context window, reasoning support, modalities, display names) live in
# data/saia-models.json, generated by merging the live SAIA API + the GWDG docs
# table + scripts/reasoning-models.json:
#     node scripts/collect-saia-model-info.mjs
# Only output limits, categories and aliases below are opinion. Unknown models
# get sane defaults instead of being skipped.
DATA_FILE="$PLUGIN_DIR/data/saia-models.json"

if command -v node >/dev/null 2>&1 && node "$SCRIPT_DIR/collect-saia-model-info.mjs" --out "$DATA_FILE"; then
    print_info "Refreshed data/saia-models.json (live API + GWDG docs)"
elif [[ -f "$DATA_FILE" ]]; then
    print_warn "Collector unavailable — using committed data/saia-models.json"
else
    print_error "No data/saia-models.json and collector failed"
    exit 1
fi

# fact_for <model-id> <jq expr over one model object>  (prints "null" if absent)
# NOTE: modalities are filtered to text|image — pi ProviderModelConfig does
# not (yet) express video/audio inputs.
fact_for() {
    jq -cr --arg id "$1" \
        "first(.models[] | select(.id == \$id) | $2) // \"null\"" "$DATA_FILE"
}

# Taste: output limits (id|max_tokens). Context windows come from the facts.
MAX_TOKENS=(
    "apertus-70b-instruct-2509|8192"
    "deepseek-v4-flash-0731|32768"
    "devstral-2-123b-instruct-2512|16384"
    "gemma-4-31b-it|8192"
    "glm-5.3-flash|32768"
    "meta-llama-3.1-8b-instruct|4096"
    "mistral-medium-3.5-128b|8192"
    "openai-gpt-oss-120b|8192"
    "qwen3-30b-a3b-instruct-2507|16384"
    "qwen3-coder-next|16384"
    "qwen3-omni-30b-a3b-instruct|4096"
    "qwen3.5-397b-a17b|32768"
    "qwen3.6-35b-a3b|16384"
    "qwen3.8-27b|32768"
)
MAX_TOKENS_DEFAULT="16384"  # new/unknown SAIA models: sane default

max_tokens_for() {
    local want="$1" row
    for row in "${MAX_TOKENS[@]}"; do
        [[ "$row" == "${want}|"* ]] && { printf '%s' "${row#*|}"; return 0; }
    done
    printf '%s' "$MAX_TOKENS_DEFAULT"
}

# Aliases
declare -A ALIASES=(
    ["best-for-coding"]="qwen3-coder-next"
    ["best-for-reasoning"]="qwen3.5-397b-a17b"
    ["best-quality"]="qwen3.5-397b-a17b"
    ["best-for-vision"]="qwen3.8-27b"
    ["best-for-agentic"]="glm-5.3-flash"
    ["fastest"]="meta-llama-3.1-8b-instruct"
    ["fastest-reasoning"]="qwen3.8-27b"
    ["budget"]="deepseek-v4-flash-0731"
)

# Categorize model based on ID
categorize() {
    local id="$1"
    case "$id" in
        *thinking*|*r1*|qwen3.5-*|qwen3.6-35b-a3b|qwen3.8-27b)
            echo "reasoning"
            ;;
        *coder*)
            echo "coder"
            ;;
        *omni*|*vl-*|*vision*|internvl*)
            echo "vision"
            ;;
        medgemma*)
            echo "medical"
            ;;
        devstral*|mistral-medium*|glm-5.3-flash)
            echo "agentic"
            ;;
        *120b|*128b|*235b|*675b)
            echo "large-context"
            ;;
        *)
            echo "general"
            ;;
    esac
}

# Get list of API model IDs
API_MODEL_IDS=$(echo "$MODELS_JSON" | jq -r '.data[].id' | sort)

FINAL_MODELS="$API_MODEL_IDS"

# Get timestamp
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Build the new model list
print_info "Generating extensions/index.ts..."

# Write header
cat > "$EXTENSIONS_FILE.tmp" <<EOF
/**
 * pi-saia-plugin: SAIA (Academic Cloud Hessen) provider registration.
 *
 * Registers the SAIA provider with all models from the live SAIA API.
 * API key is read from auth.json (key: "saia"), \$SAIA_API_KEY, or /login saia.
 *
 * Install: pi install /path/to/pi-saia-plugin
 * Reload:  /reload
 *
 * This file is auto-generated by scripts/sync-saia-models.sh
 * Last sync: $TIMESTAMP
 */

import type { ExtensionAPI, ProviderModelConfig } from "@earendil-works/pi-coding-agent";

// ---------------------------------------------------------------------------
// Model catalog — Auto-synced from SAIA API
// ---------------------------------------------------------------------------

const SAIA_MODELS: ProviderModelConfig[] = [
EOF

# Track last category for grouping
LAST_CATEGORY=""

# Process all models
echo "$FINAL_MODELS" | while read -r model_id; do
    [[ -z "$model_id" ]] && continue
    
    context=$(fact_for "$model_id" '.context_window.tokens')
    if [[ "$context" == "null" ]]; then
        print_warn "No context-window facts for $model_id (skipping — update GWDG docs or the collector)"
        continue
    fi
    {
        description=$(fact_for "$model_id" '.name + " (SAIA)"')
        reasoning=$(fact_for "$model_id" '.reasoning.supported == true | tostring')
        input_types=$(echo "$MODELS_JSON" | jq -r --arg id "$model_id" 'first(.data[] | select(.id == $id) | .input // ["text"]) | map(select(. == "text" or . == "image")) | if length == 0 then ["text"] else . end | join(",")')
        max_tokens=$(max_tokens_for "$model_id")
        category=$(categorize "$model_id")
        
        # Add category comment if it's a new category
        if [[ "$category" != "$LAST_CATEGORY" ]]; then
            echo "" >> "$EXTENSIONS_FILE.tmp"
            category_title=$(echo "$category" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1' | sed 's/ / /g')
            echo "  // ── ${category_title} ────────────────────────────────────────────────────" >> "$EXTENSIONS_FILE.tmp"
            LAST_CATEGORY="$category"
        fi
        
        # Format input types as JSON array
        input_json=$(echo "$input_types" | sed 's/,/", "/g' | sed 's/^/["/' | sed 's/$/"]/')
        
        echo "  {" >> "$EXTENSIONS_FILE.tmp"
        echo "    id: \"$model_id\"," >> "$EXTENSIONS_FILE.tmp"
        echo "    name: \"$description\"," >> "$EXTENSIONS_FILE.tmp"
        echo "    reasoning: $reasoning," >> "$EXTENSIONS_FILE.tmp"
        echo "    input: $input_json," >> "$EXTENSIONS_FILE.tmp"
        echo "    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }," >> "$EXTENSIONS_FILE.tmp"
        echo "    contextWindow: $context," >> "$EXTENSIONS_FILE.tmp"
        echo "    maxTokens: $max_tokens," >> "$EXTENSIONS_FILE.tmp"
        echo "  }," >> "$EXTENSIONS_FILE.tmp"
    }
done

# Add aliases section
echo "" >> "$EXTENSIONS_FILE.tmp"
echo "  // ── Aliases (convenience shortcuts) ──────────────────────────────────" >> "$EXTENSIONS_FILE.tmp"

for alias in "${!ALIASES[@]}"; do
    target="${ALIASES[$alias]}"
    
    # Check if target model exists in our final list
    if echo "$FINAL_MODELS" | grep -qx "$target"; then
        context=$(fact_for "$target" '.context_window.tokens')
        description=$(fact_for "$target" '.name + " (SAIA)"')
        reasoning=$(fact_for "$target" '.reasoning.supported == true | tostring')
        input_types=$(echo "$MODELS_JSON" | jq -r --arg id "$target" 'first(.data[] | select(.id == $id) | .input // ["text"]) | map(select(. == "text" or . == "image")) | if length == 0 then ["text"] else . end | join(",")')
        max_tokens=$(max_tokens_for "$target")
        
        # Format input types as JSON array
        input_json=$(echo "$input_types" | sed 's/,/", "/g' | sed 's/^/["/' | sed 's/$/"]/')
        
        echo "  {" >> "$EXTENSIONS_FILE.tmp"
        echo "    id: \"$alias\"," >> "$EXTENSIONS_FILE.tmp"
        echo "    name: \"$alias → $target\"," >> "$EXTENSIONS_FILE.tmp"
        echo "    reasoning: $reasoning," >> "$EXTENSIONS_FILE.tmp"
        echo "    input: $input_json," >> "$EXTENSIONS_FILE.tmp"
        echo "    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }," >> "$EXTENSIONS_FILE.tmp"
        echo "    contextWindow: $context," >> "$EXTENSIONS_FILE.tmp"
        echo "    maxTokens: $max_tokens," >> "$EXTENSIONS_FILE.tmp"
        echo "  }," >> "$EXTENSIONS_FILE.tmp"
    fi
done

# Close the array and add provider registration
cat >> "$EXTENSIONS_FILE.tmp" <<'EOF'
];

// ---------------------------------------------------------------------------
// Provider registration
// ---------------------------------------------------------------------------

export default function (pi: ExtensionAPI) {
  pi.registerProvider("saia", {
    name: "SAIA Academic Cloud",
    baseUrl: "https://chat-ai.academiccloud.de/v1",
    apiKey: "$SAIA_API_KEY",
    api: "openai-completions",
    models: SAIA_MODELS,
  });
}
EOF

# Replace original file
mv "$EXTENSIONS_FILE.tmp" "$EXTENSIONS_FILE"

print_info "✓ Successfully updated $EXTENSIONS_FILE"
print_info "  Models synced: $MODEL_COUNT"
print_info "  Timestamp: $TIMESTAMP"

# Show summary
print_info "Model summary:"
echo "$FINAL_MODELS" | while read -r id; do
    if [[ "$(fact_for "$id" '.context_window.tokens')" != "null" ]]; then
        echo "  ✓ $id"
    else
        echo "  ⚠ $id (no metadata)"
    fi
done
